drop table if exists Artpieces;
create table Artpieces
( ArtpieceID int unsigned not null auto_increment primary key,
Title varchar(50),
Artist varchar(50),
Year int(7),
Medium varchar(50),
Description text
);
insert into Artpieces values (NULL,"Blue Morning Glory","Georgia O&rsquo;Keeffe",1938,"Oil on canvas", "This painting is an example of the Precisionism style, for which O&rsquo;Keeffe was quite popular for. Its genre is still life, and it is one of the most popular paintings featuring flowers. In fact O&rsquo;Keeffe loved to paint flowers, and all her paintings feature precise and sharply defined objects. This painting is essentially an enlargement of the blue morning glory flower. The sheer size of the flower that O&rsquo;Keeffe depicted is enough to catch anyones attention, and the way the colors are used makes it even more enchanting.");


insert into Artpieces values (NULL,"Composition IV","Wassily Kandinsky",1911,"Oil on canvas", "Composition IV is a symphony of confused shapes and colors. Many of the shapes evoke ideas of musicians and musical instruments. The artist had become frustrated working on it. While he was out, fellow artist Gabriele M&uuml;nter tidied his studio, and turned the painting sideways. When he saw it, Kandinsky then realized this was what he had been trying to achieve.");

insert into Artpieces values (NULL,"Spider","Louise Bourgeois",1997,"Bronze with a silver nitrate patina", "Spider is a sculpture by Louise Bourgeois. Executed in 1996 as an edition of six and cast in 1997; bronze with a silver nitrate patina, with the first of the edition being steel.");

insert into Artpieces values (NULL,"Eagles","Robert Davidson",1991,"Gouache, watercolor on paper", "Eagles in the Haida tradition");

insert into Artpieces values (NULL,"Balloon Dog","Jeff Koons",1994,"Stainless steel, transparent color coating.", "A 10-foot-tall version of Jeff Koons's &ldquo;Balloon Dog&rdquo; sculpture on the roof of the Metropolitan Museum of Art.");


insert into Artpieces values (NULL,"Dragonfly Woman","RRen&eacute; Lalique",1898,"Gold, enamel, chrysoprase, moonstones, and diamonds", "The brooch embodies many of the themes that characterize the Art Nouveau style. Nature, metamorphosis, and eroticism are all expressed in this disturbing, fantastical image of a bare-breasted woman emerging from a large dragonfly. When it was shown at the Paris Worlds Fair of 1900, one English visitor to the fair commented, &quot;Very remarkable and startling to the observer, but is it jewelry?&quot;");

insert into Artpieces values (NULL,"Fountain","Marcel Duchamp",1917,"Porcelain", "Submitted for the exhibition of the Society of Independent Artists, in 1917, the first annual exhibition by the Society to be staged at The Grand Central Palace in New York, Fountain was rejected by the committee, even though the rules stated that all works would be accepted from artists who paid the fee. Fountain was displayed and photographed at Alfred Stieglitz's studio, and the photo published in The Blind Man, but the original has been lost. The work is regarded by art historians and theorists of the avant-garde, such as Peter Bürger, as a major landmark in 20th-century art. 17 replicas commissioned by Duchamp in the 1960s now exist.");

insert into Artpieces values (NULL,"Self-Portrait with Thorn Necklace and Hummingbird","Frida Kahlo",1940,"Oil on canvas", "Frida Kahlo put so many symbolic creatures in this painting. She was not painting a realistic scene but using these symbolic elements to express her feelings. A bird is often symbolize freedom and life. Especially hummingbird which is colorful and always hovering above flowers. But in this painting the humming bird is black and lifeless. This might be a symbol of Frida herself. Frida spent most of her life in physical pain after the bus accident happened when she was eighteen. After that she endured about thirty-five operations to fix her body. She spent so many years bedridden and cannot bear any children. This is a painting about her suffering.");

insert into Artpieces values (NULL,"Un Bar aux Folies-Berg&egrave;re","&Eacute;douard Manet",1882,"Oil on canvas", "The painting exemplifies Manet's commitment to Realism in its detailed representation of a contemporary scene. Many features have puzzled critics but almost all of them have been shown to have a rationale, and the painting has been the subject of numerous popular and scholarly articles.");


insert into Artpieces values (NULL,"Impression, Sunrise","Claude Monet",1872,"Oil on canvas", "Impression, Sunrise (French: Impression, soleil levant) is a painting by Claude Monet. Shown at what would later be known as the 'Exhibition of the Impressionists' in April 1874, the painting is attributed to giving rise to the name of the Impressionist movement. Impression, Sunrise depicts the port of Le Havre, Monet's hometown, and is his most famous painting of the harbor.");

insert into Artpieces values (NULL,"Two Irises","Claudia McKinstry",1997,"Oil on canvas", "Mrs. McKinstry's work in floral images is remarkable; her detailed, enlarged acrylics of Iris, Sunflowers, Daffodils and others are striking in that so much personality is evident in each surreal effort. The flowers seem practically capable of speech.");

insert into Artpieces values (NULL,"Candy Lab","Tanya Schultz",2014,"Sugar and candy", "Australian artist Tanya Schultz creates immersive wonderlands using the sweetest materials: colorful sugar and candy. But along with the hundreds of pounds of sugar, the miniature worlds, which are reminiscent of mythological lands made from food, often incorporate as many ingredients as there are colors. Working under the pseudonym Pip & Pop, Schultz uses everything from glitter and pipe cleaners to beads and figurines to create her psychedelic installations, which have been exhibited all around the world.");

insert into Artpieces values (NULL,"Visual Temperature&mdash;Sofa","Cao Hui",2014,"mixed materials of resin, fibre etc.", "The work of Cao Hui could be considered indigestible for some viewers. The chinese artist's 'visual temperature' series depicts everyday objects such as an upholstered armchair, suitcase, jacket and gloves... except hyper-realistically rendered as flesh. While initially grotesque, the family of sculptures are crafted with a precision from materials that wouldn't normally be associated with soft and meaty parts: a mixture of resin, fibre and other mediums. Through his creative practice, self&ndash;deception is of primary importance in which he firmly believes that the surface of something is just as important as the interior &mdash; realistically and honestly displaying skin tissue and fat in a way that triggers emotions of 'surprise, sorrow, anger, sadness or laughter'.");

insert into Artpieces values (NULL,"Bad Mice","Rosie Fisher-Sergent",2015,"Water Color", "Three bad mice");

insert into Artpieces values (NULL,"Sagrada Familia","Antoni Gaud&iacute;",1882,"Stone etc.", "Construction of Sagrada Família had commenced in 1882 and Gaud&iacute; became involved in 1883, taking over the project and transforming it with his architectural and engineering style, combining Gothic and curvilinear Art Nouveau forms. Gaud&iacute; devoted his last years to the project, and at the time of his death at age 73 in 1926, less than a quarter of the project was complete. Sagrada Fam&iacute;lia's construction progressed slowly, as it relied on private donations and was interrupted by the Spanish Civil War, only to resume intermittent progress in the 1950s. Construction passed the midpoint in 2010 with some of the project's greatest challenges remaining and an anticipated completion date of 2026, the centenary of Gaud&iacute;'s death.");

insert into Artpieces values (NULL,"The Temptation of St. Anthony","Salvador Dal&iacute;",1946,"Oil on canvas", "Depicts a desert-like landscape: a low horizon line with high clouds and dark, warm tones in an azure sky. The figure of St. Anthony kneels in the bottom left corner. He holds an up cross in his right hand and with his left hand supports himself on an ambiguous form. A human skull lies by his right foot. A parade of elephants led by a horse approach St. Anthony. The elephants carry symbolic objects representing temptation: a statue of a nude woman holding her breasts, an obelisk, a building complex confining a nude, disembodied female torso, and a vertical tower. The animals have exaggerated, long, spindly legs, making them appear weightless.");

insert into Artpieces values (NULL,"Almond Blossoms","Vincent van Gogh",1890,"Oil on canvas", "Almond Blossoms is from a group of several paintings made in 1888 and 1890 by Vincent van Gogh in Arles and Saint-R&eacute;my, southern France of blossoming almond trees. Flowering trees were special to Van Gogh. They represented awakening and hope. He enjoyed them aesthetically and found joy in painting flowering trees. The works reflect Impressionist, Divisionist and Japanese woodcut influences. Almond Blossoms was made to celebrate the birth of his nephew and namesake, son of his brother Theo and sister-in-law Jo.");

insert into Artpieces values (NULL,"Landscape with a Stone Bridge","Rembrandt",1638,"Oil on oak panel", "Rembrandt painted only a few landscapes, mostly imaginary mountain scenes. Although The Stone Bridge is composed of elements studied from reality, it probably does not represent a specific place. The painting’s magical quality derives from its dramatic illumination: a beam of sunlight breaks through the clouds, making the approaching storm seem twice as menacing.");

insert into Artpieces values (NULL,"Cueva de las Manos (Spanish for Cave of the Hands)","Unknown",7300 BC,"Pigment on rock", "The images of hands are negative painted, that is, stencilled. Most of the hands are left hands, which suggests that painters held the spraying pipe with their right hand or they put the back of their right hand to the wall and held the spraying pipe with their left hand.");

insert into Artpieces values (NULL,"F. Champenois Imprimeur-&Eacute;diteur","Alphonse Mucha",1897,"Lithograph", "Mucha produced many paintings, illustrations, advertisements, and designs, and his lithographies in particular are considered a formative influence in Art Nouveau. Mucha used female subjects on posters advertising such diverse items as alcoholic beverages (one is for Trappist beer, others for sparkling wines and other beers) and baby food in the late 1890s. This work is typical in framing the subject in a circle, richly decorated with what sometimes are symbolist elements.");

